/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.client.FMLClientHandler
 *  cpw.mods.fml.client.registry.RenderingRegistry
 *  net.minecraft.client.model.ModelBiped
 *  net.minecraft.client.model.ModelZombie
 *  net.minecraft.client.renderer.entity.Render
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.IChatComponent
 */
package invmod.client;

import cpw.mods.fml.client.FMLClientHandler;
import cpw.mods.fml.client.registry.RenderingRegistry;
import invmod.client.render.AnimationRegistry;
import invmod.client.render.ModelIMSkeleton;
import invmod.client.render.ModelImp;
import invmod.client.render.ModelThrower;
import invmod.client.render.ModelTrap;
import invmod.client.render.RenderB;
import invmod.client.render.RenderBolt;
import invmod.client.render.RenderBoulder;
import invmod.client.render.RenderBurrower;
import invmod.client.render.RenderEgg;
import invmod.client.render.RenderGiantBird;
import invmod.client.render.RenderIMCreeper;
import invmod.client.render.RenderIMSkeleton;
import invmod.client.render.RenderIMWolf;
import invmod.client.render.RenderIMZombie;
import invmod.client.render.RenderIMZombiePigman;
import invmod.client.render.RenderImp;
import invmod.client.render.RenderInvis;
import invmod.client.render.RenderPigEngy;
import invmod.client.render.RenderSpiderIM;
import invmod.client.render.RenderThrower;
import invmod.client.render.RenderTrap;
import invmod.client.render.animation.Animation;
import invmod.client.render.animation.AnimationAction;
import invmod.client.render.animation.AnimationPhaseInfo;
import invmod.client.render.animation.BonesBirdLegs;
import invmod.client.render.animation.BonesMouth;
import invmod.client.render.animation.BonesWings;
import invmod.client.render.animation.InterpType;
import invmod.client.render.animation.KeyFrame;
import invmod.client.render.animation.Transition;
import invmod.common.ProxyCommon;
import invmod.common.entity.EntityIMBird;
import invmod.common.entity.EntityIMBolt;
import invmod.common.entity.EntityIMBoulder;
import invmod.common.entity.EntityIMBurrower;
import invmod.common.entity.EntityIMCreeper;
import invmod.common.entity.EntityIMEgg;
import invmod.common.entity.EntityIMGiantBird;
import invmod.common.entity.EntityIMImp;
import invmod.common.entity.EntityIMPigEngy;
import invmod.common.entity.EntityIMSkeleton;
import invmod.common.entity.EntityIMSpawnProxy;
import invmod.common.entity.EntityIMSpider;
import invmod.common.entity.EntityIMThrower;
import invmod.common.entity.EntityIMTrap;
import invmod.common.entity.EntityIMWolf;
import invmod.common.entity.EntityIMZombie;
import invmod.common.entity.EntityIMZombiePigman;
import invmod.common.entity.EntitySFX;
import java.io.File;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.List;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelZombie;
import net.minecraft.client.renderer.entity.Render;
import net.minecraft.entity.Entity;
import net.minecraft.util.IChatComponent;

public class ProxyClient
extends ProxyCommon {
    @Override
    public void registerEntityRenderingHandler(Class<? extends Entity> entityClass, Render renderer) {
        RenderingRegistry.registerEntityRenderingHandler(entityClass, (Render)renderer);
    }

    public void printGuiMessage(IChatComponent message) {
        FMLClientHandler.instance().getClient().field_71456_v.func_146158_b().func_146227_a(message);
    }

    @Override
    public void registerEntityRenderers() {
        RenderingRegistry.registerEntityRenderingHandler(EntityIMZombie.class, (Render)new RenderIMZombie((ModelBiped)new ModelZombie(0.0f, true), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIMZombiePigman.class, (Render)new RenderIMZombiePigman((ModelBiped)new ModelZombie(0.0f, true), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIMSkeleton.class, (Render)new RenderIMSkeleton((ModelBiped)new ModelIMSkeleton(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIMSpider.class, (Render)new RenderSpiderIM());
        RenderingRegistry.registerEntityRenderingHandler(EntityIMPigEngy.class, (Render)new RenderPigEngy(new ModelBiped(), 0.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIMImp.class, (Render)new RenderImp(new ModelImp(), 0.3f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIMThrower.class, (Render)new RenderThrower(new ModelThrower(), 1.5f));
        RenderingRegistry.registerEntityRenderingHandler(EntityIMBurrower.class, (Render)new RenderBurrower());
        RenderingRegistry.registerEntityRenderingHandler(EntityIMWolf.class, (Render)new RenderIMWolf());
        RenderingRegistry.registerEntityRenderingHandler(EntityIMBoulder.class, (Render)new RenderBoulder());
        RenderingRegistry.registerEntityRenderingHandler(EntityIMTrap.class, (Render)new RenderTrap(new ModelTrap()));
        RenderingRegistry.registerEntityRenderingHandler(EntityIMBolt.class, (Render)new RenderBolt());
        RenderingRegistry.registerEntityRenderingHandler(EntitySFX.class, (Render)new RenderInvis());
        RenderingRegistry.registerEntityRenderingHandler(EntityIMSpawnProxy.class, (Render)new RenderInvis());
        RenderingRegistry.registerEntityRenderingHandler(EntityIMEgg.class, (Render)new RenderEgg());
        RenderingRegistry.registerEntityRenderingHandler(EntityIMCreeper.class, (Render)new RenderIMCreeper());
        RenderingRegistry.registerEntityRenderingHandler(EntityIMBird.class, (Render)new RenderB());
        RenderingRegistry.registerEntityRenderingHandler(EntityIMGiantBird.class, (Render)new RenderGiantBird());
    }

    @Override
    public void loadAnimations() {
        EnumMap<BonesBirdLegs, List<KeyFrame>> allKeyFrames = new EnumMap<BonesBirdLegs, List<KeyFrame>>(BonesBirdLegs.class);
        ArrayList<AnimationPhaseInfo> animationPhases = new ArrayList<AnimationPhaseInfo>(2);
        int x = 17;
        float totalFrames = 331 + x;
        HashMap<AnimationAction, Transition> transitions = new HashMap<AnimationAction, Transition>(1);
        Transition defaultTransition = new Transition(AnimationAction.STAND, 1.0f / totalFrames, 0.0f);
        transitions.put(AnimationAction.STAND, defaultTransition);
        transitions.put(AnimationAction.STAND_TO_RUN, new Transition(AnimationAction.STAND_TO_RUN, 1.0f / totalFrames, 1.0f / totalFrames));
        transitions.put(AnimationAction.LEGS_RETRACT, new Transition(AnimationAction.LEGS_RETRACT, 1.0f / totalFrames, (211.0f + (float)x) / totalFrames));
        transitions.put(AnimationAction.LEGS_CLAW_ATTACK_P1, new Transition(AnimationAction.LEGS_CLAW_ATTACK_P1, 1.0f / totalFrames, (171.0f + (float)x) / totalFrames));
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.STAND, 0.0f, 1.0f / totalFrames, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.RUN, 38.0f / totalFrames, 38.0f / totalFrames);
        transitions.put(AnimationAction.RUN, defaultTransition);
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.STAND_TO_RUN, 1.0f / totalFrames, 38.0f / totalFrames, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.RUN, (170.0f + (float)x) / totalFrames, 38.0f / totalFrames);
        transitions.put(AnimationAction.RUN, defaultTransition);
        transitions.put(AnimationAction.STAND, new Transition(AnimationAction.STAND, (170.0f + (float)x) / totalFrames, 0.0f));
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.RUN, 38.0f / totalFrames, (170.0f + (float)x) / totalFrames, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.LEGS_UNRETRACT, (251.0f + (float)x) / totalFrames, (251.0f + (float)x) / totalFrames);
        transitions.put(AnimationAction.LEGS_UNRETRACT, defaultTransition);
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.LEGS_RETRACT, (211.0f + (float)x) / totalFrames, (251.0f + (float)x) / totalFrames, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.STAND, (291.0f + (float)x) / totalFrames, 0.0f);
        transitions.put(AnimationAction.STAND, defaultTransition);
        transitions.put(AnimationAction.LEGS_RETRACT, new Transition(AnimationAction.LEGS_RETRACT, (291.0f + (float)x) / totalFrames, (211.0f + (float)x) / totalFrames));
        transitions.put(AnimationAction.LEGS_CLAW_ATTACK_P1, new Transition(AnimationAction.LEGS_CLAW_ATTACK_P1, (291.0f + (float)x) / totalFrames, (291.0f + (float)x) / totalFrames));
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.LEGS_UNRETRACT, (251.0f + (float)x) / totalFrames, (291.0f + (float)x) / totalFrames, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.LEGS_CLAW_ATTACK_P2, (331.0f + (float)x) / totalFrames, (171.0f + (float)x) / totalFrames);
        transitions.put(AnimationAction.LEGS_CLAW_ATTACK_P2, defaultTransition);
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.LEGS_CLAW_ATTACK_P1, (291.0f + (float)x) / totalFrames, (331.0f + (float)x) / totalFrames, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.STAND, (211.0f + (float)x) / totalFrames, 0.0f);
        transitions.put(AnimationAction.STAND, defaultTransition);
        transitions.put(AnimationAction.LEGS_RETRACT, new Transition(AnimationAction.LEGS_RETRACT, (211.0f + (float)x) / totalFrames, (211.0f + (float)x) / totalFrames));
        transitions.put(AnimationAction.LEGS_CLAW_ATTACK_P1, new Transition(AnimationAction.LEGS_CLAW_ATTACK_P1, (211.0f + (float)x) / totalFrames, (291.0f + (float)x) / totalFrames));
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.LEGS_CLAW_ATTACK_P2, (171.0f + (float)x) / totalFrames, (211.0f + (float)x) / totalFrames, defaultTransition, transitions));
        float frameUnit = 1.0f / totalFrames;
        float runBegin = 38.0f * frameUnit;
        float runEnd = (float)(170 + x) * frameUnit;
        ArrayList<KeyFrame> leftThighFrames = new ArrayList<KeyFrame>(13);
        leftThighFrames.add(new KeyFrame(0.0f, -15.0f, 0.0f, -5.0f, InterpType.LINEAR));
        leftThighFrames.add(new KeyFrame(1.0f * frameUnit, -15.0f, 0.0f, -5.0f, InterpType.LINEAR));
        leftThighFrames.add(new KeyFrame(5.0f * frameUnit, -12.6f, 0.2f, 5.0f, InterpType.LINEAR));
        leftThighFrames.add(new KeyFrame(10.0f * frameUnit, 21.2f, -0.6f, 5.2f, InterpType.LINEAR));
        leftThighFrames.add(new KeyFrame(15.0f * frameUnit, -32.0f, -1.7f, 5.7f, InterpType.LINEAR));
        leftThighFrames.add(new KeyFrame(25.0f * frameUnit, -57.0f, -6.4f, 9.0f, InterpType.LINEAR));
        leftThighFrames.add(new KeyFrame(35.0f * frameUnit, -76.5f, -19.3f, 21.2f, InterpType.LINEAR));
        KeyFrame.toRadians(leftThighFrames);
        ArrayList<KeyFrame> leftThighRunCycle = new ArrayList<KeyFrame>(7);
        leftThighRunCycle.add(new KeyFrame(38.0f * frameUnit, -74.1f, 0.0f, -6.5f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame(44.0f * frameUnit, -63.7f, 0.0f, -6.5f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(80 + x) * frameUnit, 13.1f, 0.0f, -6.5f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(101 + x) * frameUnit, 35.7f, 0.0f, -6.5f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(110 + x) * frameUnit, 20.0f, 0.0f, -6.5f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(140 + x) * frameUnit, -33.0f, 0.0f, -6.5f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(170 + x) * frameUnit, -74.1f, 0.0f, -6.5f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(171 + x) * frameUnit, -76.0f, 0.0f, -5.6f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(211 + x) * frameUnit, -15.0f, 0.0f, -5.0f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(251 + x) * frameUnit, 9.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(291 + x) * frameUnit, -15.0f, 0.0f, -5.0f, InterpType.LINEAR));
        leftThighRunCycle.add(new KeyFrame((float)(331 + x) * frameUnit, -76.0f, 0.0f, -5.6f, InterpType.LINEAR));
        KeyFrame.toRadians(leftThighRunCycle);
        ArrayList<KeyFrame> rightThighFrames = new ArrayList<KeyFrame>(13);
        rightThighFrames.add(new KeyFrame(0.0f, -15.0f, 0.0f, 0.0f, InterpType.LINEAR));
        rightThighFrames.add(new KeyFrame(1.0f * frameUnit, -15.0f, 0.0f, 0.0f, InterpType.LINEAR));
        rightThighFrames.add(new KeyFrame(37.0f * frameUnit, -15.0f, 0.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(rightThighFrames);
        List<KeyFrame> rightThighRunCycle = KeyFrame.cloneFrames(leftThighRunCycle);
        KeyFrame.mirrorFramesX(rightThighRunCycle);
        KeyFrame.offsetFramesCircular(rightThighRunCycle, runBegin, runEnd, (runEnd - runBegin) / 2.0f);
        leftThighFrames.addAll(leftThighRunCycle);
        rightThighFrames.addAll(rightThighRunCycle);
        allKeyFrames.put(BonesBirdLegs.LEFT_KNEE, leftThighFrames);
        allKeyFrames.put(BonesBirdLegs.RIGHT_KNEE, rightThighFrames);
        ArrayList<KeyFrame> leftLegFrames = new ArrayList<KeyFrame>(19);
        leftLegFrames.add(new KeyFrame(0.0f, -41.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegFrames.add(new KeyFrame(1.0f * frameUnit, -41.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegFrames.add(new KeyFrame(10.0f * frameUnit, -80.3f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegFrames.add(new KeyFrame(25.0f * frameUnit, -44.2f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegFrames.add(new KeyFrame(35.0f * frameUnit, -5.6f, 0.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(leftLegFrames);
        ArrayList<KeyFrame> leftLegRunCycle = new ArrayList<KeyFrame>(16);
        leftLegRunCycle.add(new KeyFrame(38.0f * frameUnit, 6.6f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame(44.0f * frameUnit, 6.5f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame(47.0f * frameUnit, -11.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame(50.0f * frameUnit, -24.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame(53.0f * frameUnit, -32.9f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame(56.0f * frameUnit, -40.8f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame(59.0f * frameUnit, -46.7f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame(62.0f * frameUnit, -45.8f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame(82.0f * frameUnit, -45.6f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame(97.0f * frameUnit, -17.1f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(85 + x) * frameUnit, 0.75f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(90 + x) * frameUnit, -0.4f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(101 + x) * frameUnit, -43.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(115 + x) * frameUnit, -60.1f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(154 + x) * frameUnit, -50.5f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(170 + x) * frameUnit, 6.6f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(171 + x) * frameUnit, -37.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(211 + x) * frameUnit, -41.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(251 + x) * frameUnit, 15.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(291 + x) * frameUnit, -41.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftLegRunCycle.add(new KeyFrame((float)(331 + x) * frameUnit, -37.0f, 0.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(leftLegRunCycle);
        ArrayList<KeyFrame> rightLegFrames = new ArrayList<KeyFrame>(19);
        rightLegFrames.add(new KeyFrame(0.0f, -41.0f, 0.0f, 0.0f, InterpType.LINEAR));
        rightLegFrames.add(new KeyFrame(37.0f * frameUnit, -41.0f, 0.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(rightLegFrames);
        List<KeyFrame> rightLegRunCycle = KeyFrame.cloneFrames(leftLegRunCycle);
        KeyFrame.mirrorFramesX(rightLegRunCycle);
        KeyFrame.offsetFramesCircular(rightLegRunCycle, runBegin, runEnd, (runEnd - runBegin) / 2.0f);
        leftLegFrames.addAll(leftLegRunCycle);
        rightLegFrames.addAll(rightLegRunCycle);
        allKeyFrames.put(BonesBirdLegs.LEFT_ANKLE, leftLegFrames);
        allKeyFrames.put(BonesBirdLegs.RIGHT_ANKLE, rightLegFrames);
        ArrayList<KeyFrame> leftAnkleFrames = new ArrayList<KeyFrame>(27);
        leftAnkleFrames.add(new KeyFrame(0.0f, -0.4f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleFrames.add(new KeyFrame(1.0f * frameUnit, -0.4f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleFrames.add(new KeyFrame(5.0f * frameUnit, 31.7f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleFrames.add(new KeyFrame(10.0f * frameUnit, 45.0f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleFrames.add(new KeyFrame(20.0f * frameUnit, 52.8f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleFrames.add(new KeyFrame(25.0f * frameUnit, 51.6f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleFrames.add(new KeyFrame(30.0f * frameUnit, 42.3f, -5.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(leftAnkleFrames);
        ArrayList<KeyFrame> leftAnkleRunCycle = new ArrayList<KeyFrame>(21);
        leftAnkleRunCycle.add(new KeyFrame(38.0f * frameUnit, 28.8f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(44.0f * frameUnit, -0.4f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(47.0f * frameUnit, 7.6f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(50.0f * frameUnit, 12.4f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(53.0f * frameUnit, 12.6f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(56.0f * frameUnit, 11.8f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(59.0f * frameUnit, 8.5f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(62.0f * frameUnit, 1.6f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(82.0f * frameUnit, -1.0f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(87.0f * frameUnit, -5.5f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(90.0f * frameUnit, -0.7f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(93.0f * frameUnit, 6.8f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame(97.0f * frameUnit, -4.6f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(85 + x) * frameUnit, 20.7f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(95 + x) * frameUnit, 34.2f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(100 + x) * frameUnit, 45.6f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(110 + x) * frameUnit, 36.6f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(115 + x) * frameUnit, 38.4f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(124 + x) * frameUnit, 50.0f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(140 + x) * frameUnit, 45.3f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(154 + x) * frameUnit, 52.9f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(170 + x) * frameUnit, 25.0f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(171 + x) * frameUnit, -38.0f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(211 + x) * frameUnit, 0.0f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(251 + x) * frameUnit, 22.0f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(291 + x) * frameUnit, 0.0f, -5.0f, 0.0f, InterpType.LINEAR));
        leftAnkleRunCycle.add(new KeyFrame((float)(331 + x) * frameUnit, -38.0f, -5.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(leftAnkleRunCycle);
        ArrayList<KeyFrame> rightAnkleFrames = new ArrayList<KeyFrame>(27);
        rightAnkleFrames.add(new KeyFrame(0.0f, -0.4f, -5.0f, 0.0f, InterpType.LINEAR));
        rightAnkleFrames.add(new KeyFrame(1.0f * frameUnit, -0.4f, -5.0f, 0.0f, InterpType.LINEAR));
        rightAnkleFrames.add(new KeyFrame(37.0f * frameUnit, -0.4f, -5.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(rightAnkleFrames);
        List<KeyFrame> rightAnkleRunCycle = KeyFrame.cloneFrames(leftAnkleRunCycle);
        KeyFrame.mirrorFramesX(rightAnkleRunCycle);
        KeyFrame.offsetFramesCircular(rightAnkleRunCycle, runBegin, runEnd, (runEnd - runBegin) / 2.0f);
        leftAnkleFrames.addAll(leftAnkleRunCycle);
        rightAnkleFrames.addAll(rightAnkleRunCycle);
        allKeyFrames.put(BonesBirdLegs.LEFT_METATARSOPHALANGEAL_ARTICULATIONS, leftAnkleFrames);
        allKeyFrames.put(BonesBirdLegs.RIGHT_METATARSOPHALANGEAL_ARTICULATIONS, rightAnkleFrames);
        ArrayList<KeyFrame> leftBackClawFrames = new ArrayList<KeyFrame>(21);
        leftBackClawFrames.add(new KeyFrame(0.0f, 77.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftBackClawFrames.add(new KeyFrame((float)(170 + x) * frameUnit, 77.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftBackClawFrames.add(new KeyFrame((float)(171 + x) * frameUnit, 84.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftBackClawFrames.add(new KeyFrame((float)(211 + x) * frameUnit, 77.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftBackClawFrames.add(new KeyFrame((float)(251 + x) * frameUnit, -7.5f, 0.0f, 0.0f, InterpType.LINEAR));
        leftBackClawFrames.add(new KeyFrame((float)(291 + x) * frameUnit, 77.0f, 0.0f, 0.0f, InterpType.LINEAR));
        leftBackClawFrames.add(new KeyFrame((float)(331 + x) * frameUnit, 84.0f, 0.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(leftBackClawFrames);
        List<KeyFrame> rightBackClawFrames = KeyFrame.cloneFrames(leftBackClawFrames);
        KeyFrame.mirrorFramesX(rightBackClawFrames);
        allKeyFrames.put(BonesBirdLegs.LEFT_BACK_CLAW, leftBackClawFrames);
        allKeyFrames.put(BonesBirdLegs.RIGHT_BACK_CLAW, rightBackClawFrames);
        Animation<BonesBirdLegs> birdRun = new Animation<BonesBirdLegs>(BonesBirdLegs.class, 1.0f, 0.04651163f, allKeyFrames, animationPhases);
        AnimationRegistry.instance().registerAnimation("bird_run", birdRun);
        EnumMap<BonesWings, List<KeyFrame>> allKeyFramesWings = new EnumMap<BonesWings, List<KeyFrame>>(BonesWings.class);
        animationPhases = new ArrayList(3);
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.WINGFLAP, 0.2714932f, 0.0f);
        transitions.put(AnimationAction.WINGFLAP, defaultTransition);
        transitions.put(AnimationAction.WINGTUCK, new Transition(AnimationAction.WINGTUCK, 0.06787331f, 0.2760181f));
        transitions.put(AnimationAction.WINGGLIDE, new Transition(AnimationAction.WINGGLIDE, 0.06787331f, 0.8190045f));
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.WINGFLAP, 0.0f, 0.2714932f, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.WINGSPREAD, 0.5429865f, 0.5475113f);
        transitions.put(AnimationAction.WINGSPREAD, defaultTransition);
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.WINGTUCK, 0.2760181f, 0.5429865f, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.WINGTUCK, 0.8190045f, 0.2760181f);
        transitions.put(AnimationAction.WINGTUCK, defaultTransition);
        transitions.put(AnimationAction.WINGFLAP, new Transition(AnimationAction.WINGFLAP, 0.8190045f, 0.06787331f));
        transitions.put(AnimationAction.WINGGLIDE, new Transition(AnimationAction.WINGGLIDE, 0.8190045f, 0.8190045f));
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.WINGSPREAD, 0.5475113f, 0.8190045f, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.WINGGLIDE, 1.0f, 0.8190045f);
        transitions.put(AnimationAction.WINGGLIDE, defaultTransition);
        transitions.put(AnimationAction.WINGFLAP, new Transition(AnimationAction.WINGFLAP, 1.0f, 0.06787331f));
        transitions.put(AnimationAction.WINGTUCK, new Transition(AnimationAction.WINGTUCK, 1.0f, 0.2760181f));
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.WINGGLIDE, 0.8190045f, 1.0f, defaultTransition, transitions));
        frameUnit = 0.004524887f;
        ArrayList<KeyFrame> rightInnerWingFrames = new ArrayList<KeyFrame>(12);
        rightInnerWingFrames.add(new KeyFrame(0.0f, 2.0f, -48.0f, 0.0f, 7.0f, -8.0f, 6.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(5.0f * frameUnit, 4.0f, -38.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(10.0f * frameUnit, 5.5f, -27.5f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(15.0f * frameUnit, 5.5f, -7.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(20.0f * frameUnit, 5.5f, 15.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(25.0f * frameUnit, 4.5f, 30.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(30.0f * frameUnit, 2.0f, 38.0f, 9.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(35.0f * frameUnit, 1.0f, 20.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(40.0f * frameUnit, 1.0f, 3.5f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(45.0f * frameUnit, 1.0f, -19.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(50.0f * frameUnit, -3.0f, -38.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(55.0f * frameUnit, -1.0f, -48.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(60.0f * frameUnit, 2.0f, -48.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(61.0f * frameUnit, 5.5f, -7.0f, 0.0f, 7.0f, -8.0f, 6.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(121.0f * frameUnit, 0.71f, 88.6f, 0.0f, 11.0f, -8.0f, 9.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(181.0f * frameUnit, 5.5f, -7.0f, 0.0f, 7.0f, -8.0f, 6.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(209.0f * frameUnit, 5.5f, -5.0f, 0.0f, InterpType.LINEAR));
        rightInnerWingFrames.add(new KeyFrame(221.0f * frameUnit, 5.5f, -7.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(rightInnerWingFrames);
        List<KeyFrame> leftInnerWingFrames = KeyFrame.cloneFrames(rightInnerWingFrames);
        KeyFrame.mirrorFramesX(leftInnerWingFrames);
        allKeyFramesWings.put(BonesWings.LEFT_SHOULDER, rightInnerWingFrames);
        allKeyFramesWings.put(BonesWings.RIGHT_SHOULDER, leftInnerWingFrames);
        ArrayList<KeyFrame> rightOuterWingFrames = new ArrayList<KeyFrame>(13);
        rightOuterWingFrames.add(new KeyFrame(0.0f, 2.0f, 34.5f, 0.0f, 23.0f, 1.0f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(5.0f * frameUnit, 5.0f, 13.0f, -7.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(10.0f * frameUnit, 7.0f, 8.5f, -10.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(15.0f * frameUnit, 7.5f, -2.5f, -10.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(25.0f * frameUnit, 5.0f, 7.0f, -10.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(30.0f * frameUnit, 2.0f, 15.0f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(35.0f * frameUnit, -3.0f, 37.0f, 12.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(40.0f * frameUnit, -9.0f, 56.0f, 27.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(45.0f * frameUnit, -13.0f, 68.0f, 28.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(50.0f * frameUnit, -13.5f, 70.0f, 31.5f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(53.0f * frameUnit, -9.0f, 71.0f, 31.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(55.0f * frameUnit, -3.5f, 65.5f, 22.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(58.0f * frameUnit, 0.0f, 52.0f, 8.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(60.0f * frameUnit, 2.0f, 34.5f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(61.0f * frameUnit, -5.0f, -2.5f, -10.0f, 23.0f, 1.0f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(76.0f * frameUnit, 0.0f, 0.0f, 15.0f, 22.0f, 1.0f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(101.0f * frameUnit, 0.0f, 0.0f, 83.0f, 20.33f, 1.0f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(121.0f * frameUnit, 0.0f, 0.0f, 90.0f, 19.0f, 1.0f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(141.0f * frameUnit, 0.0f, 0.0f, 83.0f, 20.33f, 1.0f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(166.0f * frameUnit, 0.0f, 0.0f, 15.0f, 22.0f, 1.0f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(181.0f * frameUnit, -5.0f, -2.5f, -10.0f, 23.0f, 1.0f, 0.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(209.0f * frameUnit, -5.0f, -1.3f, -10.0f, InterpType.LINEAR));
        rightOuterWingFrames.add(new KeyFrame(221.0f * frameUnit, -5.0f, -2.5f, -10.0f, InterpType.LINEAR));
        KeyFrame.toRadians(rightOuterWingFrames);
        List<KeyFrame> leftOuterWingFrames = KeyFrame.cloneFrames(rightOuterWingFrames);
        KeyFrame.mirrorFramesX(leftOuterWingFrames);
        allKeyFramesWings.put(BonesWings.LEFT_ELBOW, rightOuterWingFrames);
        allKeyFramesWings.put(BonesWings.RIGHT_ELBOW, leftOuterWingFrames);
        Animation<BonesWings> wingFlap = new Animation<BonesWings>(BonesWings.class, 1.0f, 0.01666667f, allKeyFramesWings, animationPhases);
        AnimationRegistry.instance().registerAnimation("wing_flap_2_piece", wingFlap);
        EnumMap<BonesMouth, ArrayList<KeyFrame>> allKeyFramesBeak = new EnumMap<BonesMouth, ArrayList<KeyFrame>>(BonesMouth.class);
        animationPhases = new ArrayList(3);
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.MOUTH_CLOSE, 0.5f, 0.5083333f);
        transitions.put(AnimationAction.MOUTH_CLOSE, defaultTransition);
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.MOUTH_OPEN, 0.0f, 0.5f, defaultTransition, transitions));
        transitions = new HashMap(1);
        defaultTransition = new Transition(AnimationAction.MOUTH_OPEN, 1.0f, 0.0f);
        transitions.put(AnimationAction.MOUTH_OPEN, defaultTransition);
        animationPhases.add(new AnimationPhaseInfo(AnimationAction.MOUTH_CLOSE, 0.5f, 1.0f, defaultTransition, transitions));
        frameUnit = 0.008333334f;
        ArrayList<KeyFrame> upperBeakFrames = new ArrayList<KeyFrame>(3);
        upperBeakFrames.add(new KeyFrame(0.0f * frameUnit, 0.0f, 0.0f, 0.0f, InterpType.LINEAR));
        upperBeakFrames.add(new KeyFrame(60.0f * frameUnit, -8.0f, 0.0f, 0.0f, InterpType.LINEAR));
        upperBeakFrames.add(new KeyFrame(120.0f * frameUnit, 0.0f, 0.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(upperBeakFrames);
        allKeyFramesBeak.put(BonesMouth.UPPER_MOUTH, upperBeakFrames);
        ArrayList<KeyFrame> lowerBeakFrames = new ArrayList<KeyFrame>(3);
        lowerBeakFrames.add(new KeyFrame(0.0f * frameUnit, 0.0f, 0.0f, 0.0f, InterpType.LINEAR));
        lowerBeakFrames.add(new KeyFrame(60.0f * frameUnit, 20.0f, 0.0f, 0.0f, InterpType.LINEAR));
        lowerBeakFrames.add(new KeyFrame(120.0f * frameUnit, 0.0f, 0.0f, 0.0f, InterpType.LINEAR));
        KeyFrame.toRadians(lowerBeakFrames);
        allKeyFramesBeak.put(BonesMouth.LOWER_MOUTH, lowerBeakFrames);
        Animation<BonesMouth> beak = new Animation<BonesMouth>(BonesMouth.class, 1.0f, 0.1f, allKeyFramesBeak, animationPhases);
        AnimationRegistry.instance().registerAnimation("bird_beak", beak);
    }

    @Override
    public File getFile(String fileName) {
        return new File(FMLClientHandler.instance().getClient().field_71412_D.getPath() + fileName);
    }
}

